extends:
 - ./eslintrc-gjs.yml
 - ./eslintrc-shell.yml
parserOptions:
  sourceType: module
rules:
  comma-dangle:
   - warn
   - arrays: only-multiline
     objects: only-multiline
     imports: only-multiline
     exports: only-multiline
     functions: only-multiline
  arrow-parens:
   - warn
   - always
  nonblock-statement-body-position:
   - warn
   - beside
  operator-linebreak:
   - warn
   - before
  curly:
   - warn
   - multi-line
  object-curly-spacing:
   - warn
   - always
  quotes:
   - warn
   - backtick
  prefer-template: warn
  no-useless-return: warn
  no-undef: warn
  no-shadow: warn
  indent:
    - warn
    - 4
    - SwitchCase: 1
  eol-last: warn
  no-useless-constructor: warn
  no-implicit-coercion: warn
  object-shorthand: warn
  max-statements-per-line: warn
  brace-style: warn
  no-extra-parens: warn
  no-dupe-class-members: warn
  consistent-return: warn
  no-trailing-spaces: warn
  spaced-comment: warn
  require-await: warn
  eqeqeq: off
  no-unused-vars: off
  semi: off
  no-async-promise-executor: off
  no-return-await: off
  jsdoc/require-jsdoc: off
