extends:
 - ./eslintrc-gjs.yml
 - ./eslintrc-shell.yml
parserOptions:
  sourceType: module
rules:
  arrow-parens:
   - warn
   - always
  comma-dangle:
   - warn
   - arrays: only-multiline
     objects: only-multiline
     imports: only-multiline
     exports: only-multiline
     functions: only-multiline
  curly:
   - warn
   - multi-line
  semi: off
  prefer-template:
   - warn
  object-curly-spacing:
   - warn
   - always
  quotes:
   - warn
   - backtick
  no-useless-return:
   - warn
  no-undef:
   - warn
  no-shadow:
   - warn
  indent:
   - warn
  eol-last:
   - warn
  no-useless-constructor:
   - warn
  no-implicit-coercion:
   - warn
  object-shorthand:
   - warn
  no-unused-vars: off
  eqeqeq: off
  max-statements-per-line:
   - warn
  brace-style:
   - warn
  no-extra-parens:
   - warn
  nonblock-statement-body-position:
   - warn
   - beside
  operator-linebreak:
   - warn
   - before
  no-dupe-class-members:
   - warn
  consistent-return:
   - warn
  require-await: off
  no-trailing-spaces:
   - warn
  spaced-comment:
   - warn
  no-async-promise-executor: off
  no-return-await: off
  jsdoc/require-jsdoc: off
