extends:
 - ./eslintrc-gjs.yml
 - ./eslintrc-shell.yml
parserOptions:
  sourceType: module
rules:
  arrow-parens:
   - warn
   - always
  comma-dangle:
   - warn
   - arrays: only-multiline
     objects: only-multiline
     imports: only-multiline
     exports: only-multiline
     functions: only-multiline
  curly:
   - warn
   - multi-line
  semi: off
  prefer-template:
   - warn
  object-curly-spacing:
   - warn
   - always
  quotes:
   - warn
   - backtick
  no-useless-return:
   - warn
  no-undef:
   - warn
  no-unused-vars: off
  eqeqeq: off
  no-shadow: off
  eol-last: off
  max-statements-per-line: off
  brace-style: off
  no-extra-parens: off
  nonblock-statement-body-position: off
  operator-linebreak: off
  no-dupe-class-members: off
  indent: off
  require-await: off
  no-useless-constructor: off
  no-trailing-spaces: off
  consistent-return: off
  no-async-promise-executor: off
  no-implicit-coercion: off
  no-return-await: off
  object-shorthand: off
  spaced-comment: off
  jsdoc/require-jsdoc: off
