name: ESLint

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing node_modules
        run: npm install
      - name: Running ESLint
        run: npm run lint
      - name: Setting user.email
        run: git config --global user.email "github@github.com"
      - name: Setting user.name
        run: git config --global user.name "ES Lint"
      - name: Adding
        run: git add .
      - name: Committing
        run: git commit -m "ESLint"
      - name: Pushing
        run: git push
