name: Build GNOME Extension
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up GNOME Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gnome-shell-dev
      - name: Build GNOME Extension
        run: |
          make build
      - name: Upload Extension
        uses: actions/upload-artifact@v2
        with:
          name: gnome-extension
          path: github-actions@arononak.github.io/
