name: Build GNOME Extension
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up GNOME Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gnome-shell-extensions
      - name: Build GNOME Extension
        run: |
          cd github-actions@arononak.github.io
          make build
          mkdir ext
          unzip github-actions@arononak.github.io.shell-extension.zip -d ./ext
          rm github-actions@arononak.github.io.shell-extension.zip
      - name: Upload Extension
        uses: actions/upload-artifact@v2
        with:
          name: ./ext
          path: github-actions@arononak.github.io/
